server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: job-postings-evaluator
  cloud:
    openfeign:
      okhttp:
        enabled: true

joposcragent:
  job-postings-crud:
    base-url: ${JOPOSCRAGENT_JOB_POSTINGS_CRUD_BASE_URL:http://job-postings-crud:8080}
  settings-manager:
    base-url: ${JOPOSCRAGENT_SETTINGS_MANAGER_BASE_URL:http://settings-manager:8080}
  sentence-transformer:
    base-url: ${JOPOSCRAGENT_SENTENCE_TRANSFORMER_BASE_URL:http://sentence-transformer:8000/sentence-transformer}

celery:
  orchestrator:
    base-url: ${CELERY_ORCHESTRATOR_BASE_URL:http://celery-orchestrator-api:8000}

---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8082
joposcragent:
  job-postings-crud:
    base-url: http://localhost:8081
  settings-manager:
    base-url: http://localhost:8080
  sentence-transformer:
    base-url: http://localhost:8000/sentence-transformer
celery:
  orchestrator:
    base-url: http://localhost:8001
