server:
  port: 8082

management:
  endpoint:
    enabled-by-default: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: job-postings-evaluator
  datasource:
    url: jdbc:postgresql://localhost:5432/joposcragent
    username: postgres
    password: postgres

joposcragent:
  settings-manager:
    base-url: http://localhost:8080
  sentence-transformer:
    base-url: http://localhost:8000/sentence-transformer
